-- Crear tipo ENUM para los días
CREATE TYPE weekday AS ENUM ('Mon','Tue','Wed','Thu','Fri','Sat','Sun');

-- Tabla padre particionada
CREATE TABLE project_19_weekend_money (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    day weekday NOT NULL,
    hours TEXT NOT NULL,
    money TEXT
)
PARTITION BY LIST (day);

-- Seguridad
ALTER TABLE project_19_weekend_money ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read" ON project_19_weekend_money
FOR SELECT
USING (true);

-- Crear particiones por día
CREATE TABLE monday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Mon');

CREATE TABLE tuesday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Tue');

CREATE TABLE wednesday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Wed');

CREATE TABLE thursday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Thu');

CREATE TABLE friday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Fri');

CREATE TABLE saturday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Sat');

CREATE TABLE sunday_money_project_19
    PARTITION OF project_19_weekend_money
    FOR VALUES IN ('Sun');

-- INSERTS
INSERT INTO project_19_weekend_money (day, hours, money) VALUES
-- 08:00 - 09:00
('Mon','08:00 - 09:00', NULL),
('Tue','08:00 - 09:00', NULL),
('Wed','08:00 - 09:00', NULL),
('Thu','08:00 - 09:00','120'),
('Fri','08:00 - 09:00','130'),
('Sat','08:00 - 09:00','140'),
('Sun','08:00 - 09:00','160'),

-- 09:00 - 10:00
('Mon','09:00 - 10:00', NULL),
('Tue','09:00 - 10:00', NULL),
('Wed','09:00 - 10:00','120'),
('Thu','09:00 - 10:00','130'),
('Fri','09:00 - 10:00','140'),
('Sat','09:00 - 10:00','150'),
('Sun','09:00 - 10:00','170'),

-- 10:00 - 11:00
('Mon','10:00 - 11:00','120'),
('Tue','10:00 - 11:00','130'),
('Wed','10:00 - 11:00','130'),
('Thu','10:00 - 11:00','140'),
('Fri','10:00 - 11:00','150'),
('Sat','10:00 - 11:00','160'),
('Sun','10:00 - 11:00','180'),

-- 11:00 - 12:00
('Mon','11:00 - 12:00','130'),
('Tue','11:00 - 12:00','140'),
('Wed','11:00 - 12:00','140'),
('Thu','11:00 - 12:00','150'),
('Fri','11:00 - 12:00','160'),
('Sat','11:00 - 12:00','170'),
('Sun','11:00 - 12:00','190'),

-- 12:00 - 13:00
('Mon','12:00 - 13:00', NULL),
('Tue','12:00 - 13:00', NULL),
('Wed','12:00 - 13:00', NULL),
('Thu','12:00 - 13:00', NULL),
('Fri','12:00 - 13:00', NULL),
('Sat','12:00 - 13:00','180'),
('Sun','12:00 - 13:00','200'),

-- 13:00 - 14:00
('Mon','13:00 - 14:00','140'),
('Tue','13:00 - 14:00','150'),
('Wed','13:00 - 14:00','150'),
('Thu','13:00 - 14:00','160'),
('Fri','13:00 - 14:00','170'),
('Sat','13:00 - 14:00','190'),
('Sun','13:00 - 14:00','210'),

-- 14:00 - 15:00
('Mon','14:00 - 15:00','140'),
('Tue','14:00 - 15:00','150'),
('Wed','14:00 - 15:00','150'),
('Thu','14:00 - 15:00','160'),
('Fri','14:00 - 15:00','170'),
('Sat','14:00 - 15:00','190'),
('Sun','14:00 - 15:00','210'),

-- 15:00 - 16:00
('Mon','15:00 - 16:00','150'),
('Tue','15:00 - 16:00','160'),
('Wed','15:00 - 16:00','160'),
('Thu','15:00 - 16:00','170'),
('Fri','15:00 - 16:00','180'),
('Sat','15:00 - 16:00','200'),
('Sun','15:00 - 16:00','220'),

-- 16:00 - 17:00
('Mon','16:00 - 17:00','160'),
('Tue','16:00 - 17:00','170'),
('Wed','16:00 - 17:00','170'),
('Thu','16:00 - 17:00','180'),
('Fri','16:00 - 17:00','190'),
('Sat','16:00 - 17:00','210'),
('Sun','16:00 - 17:00','230'),

-- 17:00 - 18:00
('Mon','17:00 - 18:00','170'),
('Tue','17:00 - 18:00','180'),
('Wed','17:00 - 18:00','180'),
('Thu','17:00 - 18:00','190'),
('Fri','17:00 - 18:00','200'),
('Sat','17:00 - 18:00','220'),
('Sun','17:00 - 18:00','240'),

-- 18:00 - 19:00
('Mon','18:00 - 19:00','180'),
('Tue','18:00 - 19:00','190'),
('Wed','18:00 - 19:00','190'),
('Thu','18:00 - 19:00','200'),
('Fri','18:00 - 19:00','210'),
('Sat','18:00 - 19:00','230'),
('Sun','18:00 - 19:00','250'),

-- 19:00 - 20:00
('Mon','19:00 - 20:00', NULL),
('Tue','19:00 - 20:00', NULL),
('Wed','19:00 - 20:00','200'),
('Thu','19:00 - 20:00','210'),
('Fri','19:00 - 20:00','220'),
('Sat','19:00 - 20:00','250'),
('Sun','19:00 - 20:00','270');
