drop table if exists public.project_05_pixels;

create table public.project_05_pixels (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.project_04_users(id) on delete cascade,
  row int not null,
  col int not null,
  color text not null default 'transparent',
  updated_at timestamp with time zone default now(),
  constraint unique_pixel unique (user_id, row, col)
);

-- Insertar solo si es tu propio registro
create policy "insert own pixels"
on public.project_05_pixels
for insert
with check (auth.uid() = user_id);

-- Leer solo tus propios píxeles
create policy "select own pixels"
on public.project_05_pixels
for select
using (auth.uid() = user_id);

-- Actualizar solo tus propios píxeles
create policy "update own pixels"
on public.project_05_pixels
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Eliminar solo tus propios píxeles (opcional)
create policy "delete own pixels"
on public.project_05_pixels
for delete
using (auth.uid() = user_id);
